name: Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from GitHub
        uses: actions/checkout@v4

      - name: Copy files to GCP via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_PRIVATE_KEY }}
          source: "index.html"
          target: "/var/www/html/"
